# PLACEHOLDERs are replaced by CI/CD pipeline
baseURL: "https://BASE_URL_PLACEHOLDER"
languageCode: "en-us"
title: "Garrett Leber"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs/
      weight: 1
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Garrett Leber"
  description: "My personal website"
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/favicon.png"
  visitorCounterURL: "VISITOR_COUNTER_URL_PLACEHOLDER"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "dark"

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Garrett Leber" # Brand name for the brand | default is the title variable
    disableSearch: true # Disable search bar | default is false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Garrett Leber."
    subtitle: "I like to automate things"
    content: "I'm a passionate DevOps Engineer (and Software Developer). I enjoy building and automating infrastructure, and I'm always looking for new ways to improve workflows."
    image: /images/profile-img.jpg
    bottomImage:
      enable: false
    roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "files/GarrettLeber.pdf"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/tcpkump

  # About
  about:
    enable: true
    title: "About Me"
    #image: "/images/hero-bg.jpg"
    content: |-
      I consider myself a software engineer with a specialization in infrastructure, which tends to be a DevOps role. Most of my experience is with GCP, but I have also worked with AWS (and am a certified AWS Solutions Architect Associate). 
      
      I have experience in broad areas of infrastructure, including:

      - Infrastructure as Code
      - CI/CD
      - Configuration Management
      - Monitoring
      - Logging
      - Databases
      - Programming

      I also have experience in more specialized areas. I have several years of experience in networking, previously being CCNA certified. A couple of those years were in network security, specifically doing deep packet inpection and intrusion detection.


    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - Kubernetes
        - Terraform
        - Pulumi
        - Github Actions
        - Gitlab CI
        - Bitbucket Pipelines
        - Ansible
        - Puppet
        - Prometheus
        - Grafana
        - ELK Stack
        - Fluent-bit
        - PostgreSQL
        - MongoDB
        - BigQuery
        - Python
        - Go
        - Bash

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "DevOps Engineer"
        company: "OpenVPN"
        companyUrl: "https://openvpn.net/"
        date: "Feb 2022 - present"
        info:
          enable: false
        content: |
          - Successfully led the end-to-end migration of over 60 Datawarehouse pipelines (ETLs) to Google Cloud Platform (GCP), ensuring minimal disruption to business operations and achieving improved scalability and performance. 
          - Implemented Infrastructure as Code practices using Terraform, enabling efficient provisioning and management of infrastructure resources. Utilized Ansible for Configuration Management, ensuring consistent and reproducible configurations across all migrated hosts. 
          - Spearheaded the implementation of CI/CD pipelines within the Data Warehouse team, streamlining the development cycle by enforcing linting and testing standards and enabling automated deployments. This resulted in increased productivity and reduced time-to-market for new features and enhancements. 
          - Acted as a key ambassador to multiple teams, facilitating the seamless ingestion of logs via Fluent-Bit into Google BigQuery. Collaborated closely with stakeholders to understand requirements, design effective solutions, and ensure smooth data flow and analysis. 
          - Developed and deployed a Python microservice to GCP Cloud Functions, leveraging serverless architecture to optimize resource utilization. 
          - Introduced a robust code review process within the Datawarehouse team, ensuring rigorous quality checks for production code. This initiative significantly enhanced the reliability, maintainability, and overall quality of the data pipelines and data transformations. 

      - job: "DevOps Engineer"
        company: "Mitel"
        companyUrl: "https://www.mitel.com/"
        date: "May 2021 - Jan 2022"
        info:
          enable: false
        content: |
          - Demonstrated expertise in administering and managing all aspects of Google Cloud Platform (GCP) resources using Terraform, Ansible/Puppet, and Bitbucket Pipelines for CI/CD. Effectively streamlined infrastructure provisioning, configuration, and deployment processes to ensure efficient and reliable operations. 
          - Led the successful migration of NGINX reverse proxies to GCP by repackaging them into containers within a Kubernetes cluster (GKE). Oversaw the entire migration process, including containerization, deployment, and configuration management, resulting in improved scalability, availability, and performance of the infrastructure. 
          - Reviewed, assessed, and enhanced logging and alerting mechanisms using Puppet, maintaining New Relic log forwarding. Leveraged Terraform to create comprehensive alerts, enabling timely response and proactive monitoring of the infrastructure. This effort significantly improved visibility into system health and facilitated effective incident management. 
          - Actively participated in an on-call rotation to provide support for a fleet of hundreds of servers managed by the team. Responded to incidents promptly, performed troubleshooting and debugging, and implemented necessary remediation actions to ensure system stability and availability. 

      - job: "Network Security Engineer"
        company: "US Air Force - NetSec"
        date: "Nov 2019 - May 2021"
        info:
          enable: false
        content: |
          - Recruited to the enterprise-level Defensive Cyber Operations team, demonstrating exceptional qualifications. 
          - Scripted Splunk queries to detect and mitigate malicious events and created network detection methods for enterprise-wide use. 
          - Reviewed packet captures with Wireshark for analysis and tested the legitimacy of network traffic. 
          - Designed an innovative traffic burst detection technique for critical CVE exploits, eliminating network blind spots. 
          - Drove the adoption of a security-focused mindset among network teams. 
          - Attained ranking of top 15% of Airmen at this rank.  
          - Selected for an Early Promotion (BTZ) due to stellar performance. 

      - job: "Network Engineer"
        company: "US Air Force - NetOps"
        date: "Nov 2017 - Nov 2019"
        info:
          enable: false
        content: |
          - Managed and supported Palo Alto Firewalls and Blue Coat Proxies across 120+ locations, ensuring seamless integration and continuous monitoring. 
          - Designed and developed a firewall/proxy management portal, enabling more than 100 operators globally to efficiently manage and control network security. 
          - Orchestrated and executed software upgrades for Palo Alto Firewalls acting as gateways for approximately 30 Air Force bases in Panorama, ensuring smooth transitions and enhanced security. 
          - Investigated, analyzed, and resolved large-scale incidents, implementing effective remediation plans to mitigate the impact of outages that affected 800,000 users.

      - job: "Web Advisor"
        company: "EIG - Verio"
        date: "Oct 2016 - Apr 2017"
        info:
          enable: false
        content: |
          - Provided exceptional helpdesk support for website hosting (CentOS Linux/cPanel) by leveraging extensive technical knowledge and understanding. 
          - Attained expert status in migrations, assisting customers with seamless data transfers and setup of shared hosting sites and VPS. 
          - Conducted thorough management of DNS records and proficiently configured SSL/TLS certificates. 

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Science in Information Technology - Network Operations and Security"
        school:
          name: "Western Governors University"
          url: "https://www.wgu.edu/"
        date: "2020"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: garrett@garrettleber.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    socialNetworks:
      github: https://github.com/tcpkump

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: false
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

deployment:
  targets:
    - name: "s3"
      URL: "s3://BUCKET_PLACEHOLDER?region=us-east-1&awssdk=2"
      cloudFrontDistributionID: "CLOUDFRONT_DISTRIBUTION_ID_PLACEHOLDER"
